-- AlterTable
ALTER TABLE "tariffs" ADD COLUMN     "additional_id" BOOLEAN,
ADD COLUMN     "antivirus" BOOLEAN DEFAULT false,
ADD COLUMN     "automatic_cms" BOOLEAN,
ADD COLUMN     "backup" BOOLEAN,
ADD COLUMN     "count_db" INTEGER,
ADD COLUMN     "count_test_days" INTEGER,
ADD COLUMN     "ddos_def" BOOLEAN,
ADD COLUMN     "disk_type" INTEGER,
ADD COLUMN     "domains" INTEGER,
ADD COLUMN     "ftp_accounts" INTEGER,
ADD COLUMN     "info_cpu" TEXT,
ADD COLUMN     "info_cpu_core" TEXT,
ADD COLUMN     "info_disk_area" TEXT,
ADD COLUMN     "info_domains" TEXT,
ADD COLUMN     "info_ozu" TEXT,
ADD COLUMN     "info_panels" TEXT,
ADD COLUMN     "info_platforms" TEXT,
ADD COLUMN     "info_price" TEXT,
ADD COLUMN     "is_template" BOOLEAN DEFAULT false,
ADD COLUMN     "link" TEXT,
ADD COLUMN     "mailboxes" INTEGER,
ADD COLUMN     "price_month" DECIMAL(10,2),
ADD COLUMN     "price_year" DECIMAL(10,2),
ADD COLUMN     "sites" INTEGER,
ADD COLUMN     "ssh" BOOLEAN,
ADD COLUMN     "ssl" BOOLEAN,
ADD COLUMN     "status" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "subtitle" TEXT,
ADD COLUMN     "traffic" INTEGER,
ADD COLUMN     "type" INTEGER DEFAULT 0,
ALTER COLUMN "price" DROP NOT NULL,
ALTER COLUMN "period" DROP NOT NULL;
